class OzonEndpoints:
    PRODUCT_LIST = "/v3/product/list"
    PRODUCT_INFO_LIST = "/v3/product/info/list"
    STOCKS = "/v4/product/info/stocks"
    FBO_STOCKS_BY_WAREHOUSE = "/v1/product/info/stocks-by-warehouse/fbo"
    FBS_STOCKS_BY_WAREHOUSE = "/v2/product/info/stocks-by-warehouse/fbs"
    ANALYTICS_STOCKS = "/v1/analytics/stocks"
    WAREHOUSE_STOCK_REPORT = "/v2/analytics/stock_on_warehouses"
    FBS_POSTINGS = "/v3/posting/fbs/list"
    FBO_POSTINGS = "/v2/posting/fbo/list"
